= Steam Deck Hardware Documentation

:toc:
:toclevel: 5

{nbsp} +
{nbsp}

'''
<<<
== Overview
The Steam Deck is a fairly open platform which utilizes an x86-64 processor and functions much like a typical desktop system might.  The overall architecture is pretty standard for internal busses, storage, memory, GPU, etc.   It's designed to run a fork of Arch Linux, but pretty much any x86-based OS should be able to run on it to some degree.  In the case of Linux, it's mostly dependent on the upstream kernel and mesa.  There are a few hardware quirks as well as some portions of the hardware which rely on the Steam client to provide userspace access to, chiefly the input devices.

It's not the goal of this document to go into detail about hardware aspects that are already well know and supported, but rather cover some of the gaps that might be interesting or important to someone who wants to use the hardware in "unintended ways" that don't involve Steam or SteamOS.

== Disclaimer
I have no affiliation with Valve.  All the information here has been obtained through reverse engineering or published openly elsewhere.

The following are notes which I've made in the process of installing my own clean OS environment, tinkering, and developing https://gitlab.com/open-sd/opensd[OpenSD].  *I make no guarantee of the accuracy of any information in this document.*  There may also be hardware revisions that I'm not aware of, as well as possible future hardware revisions.  This is just some stuff I've gleaned from my own experience playing with my own Steam Deck.

{nbsp} +
{nbsp}

'''
<<<
== Processor
AMD Zen 2 0405 (semi-custom Van Gogh) APU::
* CPU: x86_64, 4 Physical Cores, 8 Threads
* GPU: 8 RDNA2 Compute Units
* RAM: SMA, 16GB LPDDR5 
* ~4-15W TPD

Valve states the CPU clocks between 2.4 and 3.5GHz, but I've observed the CPU clock as low as 1.2GHz.  While it's possible that it's an incorrect reading from the governer, it's more likely that Valve only measured clock speeds while running under a heavy environment like KDE.

./proc/cpuinfo
[%collapsible]
====
----
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 144
model name	: AMD Custom APU 0405
stepping	: 2
microcode	: 0x8900201
cpu MHz		: 1348.129
cache size	: 512 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips	: 5602.55
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 44 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 144
model name	: AMD Custom APU 0405
stepping	: 2
microcode	: 0x8900201
cpu MHz		: 1700.000
cache size	: 512 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips	: 5602.55
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 44 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

processor	: 2
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 144
model name	: AMD Custom APU 0405
stepping	: 2
microcode	: 0x8900201
cpu MHz		: 1385.957
cache size	: 512 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips	: 5602.55
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 44 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

processor	: 3
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 144
model name	: AMD Custom APU 0405
stepping	: 2
microcode	: 0x8900201
cpu MHz		: 1381.884
cache size	: 512 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips	: 5602.55
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 44 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

processor	: 4
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 144
model name	: AMD Custom APU 0405
stepping	: 2
microcode	: 0x8900201
cpu MHz		: 1411.480
cache size	: 512 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips	: 5602.55
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 44 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

processor	: 5
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 144
model name	: AMD Custom APU 0405
stepping	: 2
microcode	: 0x8900201
cpu MHz		: 1700.000
cache size	: 512 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips	: 5602.55
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 44 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

processor	: 6
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 144
model name	: AMD Custom APU 0405
stepping	: 2
microcode	: 0x8900201
cpu MHz		: 1700.000
cache size	: 512 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips	: 5602.55
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 44 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

processor	: 7
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 144
model name	: AMD Custom APU 0405
stepping	: 2
microcode	: 0x8900201
cpu MHz		: 1419.878
cache size	: 512 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips	: 5602.55
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 44 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
----
====

.glxinfo
[%collapsible]
====
----
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Custom GPU 0405 (vangogh, LLVM 14.0.6, DRM 3.48, 6.0.2-arch1-1) (0x163f)
    Version: 22.2.3
    Accelerated: yes
    Video memory: 1024MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 959 MB, largest block: 959 MB
    VBO free aux. memory - total: 7381 MB, largest block: 7381 MB
    Texture free memory - total: 959 MB, largest block: 959 MB
    Texture free aux. memory - total: 7381 MB, largest block: 7381 MB
    Renderbuffer free memory - total: 959 MB, largest block: 959 MB
    Renderbuffer free aux. memory - total: 7381 MB, largest block: 7381 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 1024 MB
    Total available memory: 8441 MB
    Currently available dedicated video memory: 959 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Custom GPU 0405 (vangogh, LLVM 14.0.6, DRM 3.48, 6.0.2-arch1-1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.2.3
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.2.3
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.2.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
----
====

.vulkaninfo --summary
[%collapsible]
====
----
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.235


Instance Extensions: count = 20
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6

Instance Layers:
----------------

Devices:
========
GPU0:
	apiVersion         = 4206816 (1.3.224)
	driverVersion      = 92282883 (0x5802003)
	vendorID           = 0x1002
	deviceID           = 0x163f
	deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName         = AMD Custom GPU 0405 (RADV VANGOGH)
	driverID           = DRIVER_ID_MESA_RADV
	driverName         = radv
	driverInfo         = Mesa 22.2.3
	conformanceVersion = 1.3.0.0
	deviceUUID         = 00000000-0400-0000-0000-000000000000
	driverUUID         = 414d442d-4d45-5341-2d44-525600000000
----
====

{nbsp} +
{nbsp}

'''
<<<
== Networking
NIC::
Realtek RTL8822CE 802.11ac PCIe Wireless Adapter
* Bus: PCIe

This has been a bit of a quirk in my experience.  Valve picked a cheap NIC that is known to have unstable Linux drivers and poor support, and it shows with all the issues people have been having with it.  Realtek is not good at giving a damn either.  

I'm sure that, in time, this will get fixed, but in my experience I found that disabling *Power Management* gave me a stable enough connection to actually detect my AP for long enough to connect to it.  I described this in my https://gitlab.com/open-sd/opensd/-/wikis/Guide:-Installing-Arch-Linux-on-a-Steam-Deck[Guide for install Arch on a Steam Deck].

Bluetooth::
Realtek/IMC Networks Bluetooth Radio (13d3:3553)
* Bus: USB3

.lsusb -v -d13d3:3553
[%collapsible]
====
----
Bus 003 Device 003: ID 13d3:3553 IMC Networks Bluetooth Radio
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.00
  bDeviceClass          224 Wireless
  bDeviceSubClass         1 Radio Frequency
  bDeviceProtocol         1 Bluetooth
  bMaxPacketSize0        64
  idVendor           0x13d3 IMC Networks
  idProduct          0x3553 
  bcdDevice            0.00
  iManufacturer           1 Realtek
  iProduct                2 Bluetooth Radio
  iSerial                 3 00e04c000001
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x00b1
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           3
      bInterfaceClass       224 Wireless
      bInterfaceSubClass      1 Radio Frequency
      bInterfaceProtocol      1 Bluetooth
      iInterface              4 Bluetooth Radio
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       224 Wireless
      bInterfaceSubClass      1 Radio Frequency
      bInterfaceProtocol      1 Bluetooth
      iInterface              4 Bluetooth Radio
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0000  1x 0 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0000  1x 0 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       1
      bNumEndpoints           2
      bInterfaceClass       224 Wireless
      bInterfaceSubClass      1 Radio Frequency
      bInterfaceProtocol      1 Bluetooth
      iInterface              4 Bluetooth Radio
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0009  1x 9 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0009  1x 9 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       2
      bNumEndpoints           2
      bInterfaceClass       224 Wireless
      bInterfaceSubClass      1 Radio Frequency
      bInterfaceProtocol      1 Bluetooth
      iInterface              4 Bluetooth Radio
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0011  1x 17 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0011  1x 17 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       3
      bNumEndpoints           2
      bInterfaceClass       224 Wireless
      bInterfaceSubClass      1 Radio Frequency
      bInterfaceProtocol      1 Bluetooth
      iInterface              4 Bluetooth Radio
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0019  1x 25 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0019  1x 25 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       4
      bNumEndpoints           2
      bInterfaceClass       224 Wireless
      bInterfaceSubClass      1 Radio Frequency
      bInterfaceProtocol      1 Bluetooth
      iInterface              4 Bluetooth Radio
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0021  1x 33 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0021  1x 33 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       5
      bNumEndpoints           2
      bInterfaceClass       224 Wireless
      bInterfaceSubClass      1 Radio Frequency
      bInterfaceProtocol      1 Bluetooth
      iInterface              4 Bluetooth Radio
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0031  1x 49 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0031  1x 49 bytes
        bInterval               1
Device Status:     0x0001
  Self Powered
----
====

{nbsp} +
{nbsp}

'''
<<<
== Storage
SSD::
m.2 2230 NVMe SSD
* Bus: PCIe Gen3
* Wrapped in shielding material

Brands seems to vary, probably due to supply issues, but they are all cheap and low-grade.  Personally, I'd never consider building or selling a machine with most of the junky SSDs I've seen in Steam Deck teardowns.

There are no apparent reserved / firmware blocks to be seen here, which is good.  Mysterious encrypted/binary firmware blobs stuffed into read-only block devices always set off alarms for me.

microSD::
O2 Micro SD/MMC Controller
* Bus: PCIe

Not familiar with this mfg, but I haven't had any issues with it.

{nbsp} +
{nbsp}

'''
<<<
[#display]
== Display
Screen::
Unknown Manufactuer 7" Touchscreen, 800x1200 (16:10) 60hz IPS LCD

Orientation::
Portrait / full page (native res)

Supported  Modes::
* 800x1280
* 800x600
* 640x480

This is still a bit of a mystery since there's no apparent EDID or DDC information.  `read-edid` and `ddcutil` cant detect it, and I've looked through sysfs and cant find much either.  Not sure who makes it, but it may be the least impressive part of the Steam Deck.  Colour reproduction is not good.  I -- and apparently a lot of other people -- get a ton of light bleed.  Solid background colours look like gradients.  Purple is probably the worst for me.  It's disappointing  the (newer) Nintendo Switch has a much nicer OLED.  Honestly, for a small touchscreen to use in an appliance, embedded project, mount in a wall for home automation, it's... okay.  For a $600+ USD gaming device, I'd hope for better.

X11 Rotation::
If you're going to run this in its native resolution, the screen needs to be rotatated in X (probably Wayland too, havent tested).  The Touchscreen also needs the input to be transformed to match the new rotation.  I cover this in my https://gitlab.com/open-sd/opensd/-/wikis/Guide:-Installing-Arch-Linux-on-a-Steam-Deck[Install Guide], but I'll put it here too.

./etc/X11/xorg.conf.d/30-monitor.conf
----
Section "Monitor"
    Identifier      "eDP-1"
    Option          "Rotate" "right"
EndSection
----

./etc/X11/xorg.conf.d/90-touchscreen.conf
----
Section "InputClass"
    Identifier          "Coordinate Transformation Matrix"
    MatchIsTouchscreen  "on"
    MatchDevicePath     "/dev/input/event*"
    MatchDriver         "libinput"
    Option              "CalibrationMatrix" "0 1 0 -1 0 1 0 0 1"
EndSection
----

{nbsp} +
{nbsp}

'''
<<<
== Audio
Chip::
AMD ACP/ACP3X/ACP6x Audio Coprocessor 
* part of the Van Gogh SoC

.aplay -l
[%collapsible%open]
====
To list playback devices:
----
**** List of PLAYBACK Hardware Devices ****
card 0: Generic [HD-Audio Generic], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Generic [HD-Audio Generic], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Generic [HD-Audio Generic], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Generic [HD-Audio Generic], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: acp5x [acp5x], device 0: Playback/Capture nau8821-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: acp5x [acp5x], device 1: CS35L41 Stereo Playback multicodec-1 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
----
Card 1, Device 1 is for internal playback on the built-in speakers.
====

and

.arecord -l
[%collapsible%open]
====
----
**** List of CAPTURE Hardware Devices ****
card 1: acp5x [acp5x], device 0: Playback/Capture nau8821-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
----
====

.lsmod | grep snd
[%collapsible%open]
====
kernel 6.0.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 16 Nov 2022 17:01:17 +0000 x86_64 GNU/Linux
----
snd_soc_acp5x_mach     20480  0
snd_acp5x_i2s          16384  2
snd_acp5x_pcm_dma      16384  1
snd_sof_amd_renoir     16384  0
snd_sof_amd_acp        53248  1 snd_sof_amd_renoir
snd_sof_pci            24576  1 snd_sof_amd_renoir
snd_hda_codec_hdmi     86016  1
snd_soc_cs35l41_spi    16384  2
snd_sof               307200  3 snd_sof_amd_acp,snd_sof_pci,snd_sof_amd_renoir
snd_soc_cs35l41        65536  1 snd_soc_cs35l41_spi
snd_hda_intel          61440  0
snd_sof_utils          20480  1 snd_sof
snd_soc_wm_adsp        49152  1 snd_soc_cs35l41
snd_intel_dspcfg       36864  2 snd_hda_intel,snd_sof
snd_rpl_pci_acp6x      20480  0
snd_acp_pci            16384  0
cs_dsp                 73728  1 snd_soc_wm_adsp
snd_intel_sdw_acpi     20480  1 snd_intel_dspcfg
snd_soc_nau8821        57344  2 snd_soc_acp5x_mach
snd_soc_cs35l41_lib    36864  2 snd_soc_cs35l41_spi,snd_soc_cs35l41
snd_pci_acp6x          20480  0
snd_hda_codec         188416  2 snd_hda_codec_hdmi,snd_hda_intel
snd_pci_acp5x          20480  0
snd_rn_pci_acp3x       24576  0
snd_soc_core          393216  7 snd_acp5x_i2s,snd_soc_nau8821,snd_soc_wm_adsp,snd_sof,snd_acp5x_pcm_dma,snd_soc_cs35l41,snd_soc_acp5x_mach
snd_hda_core          118784  3 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec
snd_acp_config         16384  3 snd_rn_pci_acp3x,snd_acp_pci,snd_sof_amd_renoir
snd_compress           28672  2 snd_soc_wm_adsp,snd_soc_core
snd_soc_acpi           16384  2 snd_acp_config,snd_sof_amd_renoir
ac97_bus               16384  1 snd_soc_core
snd_hwdep              16384  1 snd_hda_codec
snd_pcm_dmaengine      16384  1 snd_soc_core
snd_pci_acp3x          20480  0
snd_pcm               172032  15 snd_sof_amd_acp,snd_soc_nau8821,snd_hda_codec_hdmi,snd_pci_acp6x,snd_hda_intel,snd_hda_codec,snd_sof,snd_acp5x_pcm_dma,snd_compress,snd_soc_core,snd_sof_utils,snd_hda_core,snd_soc_cs35l41,snd_soc_acp5x_mach,snd_pcm_dmaengine
snd_timer              49152  1 snd_pcm
snd                   131072  11 snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_soc_wm_adsp,snd_hda_codec,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm,snd_soc_acp5x_mach
soundcore              16384  1 snd
----

As you can see there are a number of sound modules associated with the SoC, including a Nuvoton audio codec (nau8821)
====



This one is a bit of a problem. 

Valve chose an audio chip that had no support before they began.  They've put patches into their downstream kernel when they *should* have been focussing on getting mainline kernel support before anything -- or, controversially, just pick one of the *thousands* of perfectly functional and well supported audio devices that _already exist_.  But Valve still ended up with a ridiculous amount of audio problems.  The first preview units of the final design were demo'd back around the middle of 2021, when several of the drivers had not even been submitted by the mfgs yet.  As of November 2022, this is *still* a sore spot.  The mainline kernel has just very recently got support and it's still broken.  

Currently on the very latest kernel 6.0.9, I only get audio out of the left speaker, mono channel rendering is not supported, device drops out, etc.  These are also problems SteamOS users are experience too, apparently, which absolutely points to sloppy hardware design.  I'd expect this of some obscure hardware manufacturer that wont acknowledge Linux even exists, but for a flagship Linux-only product, this reflects poorly on Valve since they've had around three years to get this working or pick better hardware.  

Mainline kernel support is not far off now.  We'll get there.

Testing::
From the terminal using tools from the `alsa-utils` package (Arch and Debian)
[source,shell]
----
$ speaker-test -Dhw:1,1 -c2
----

I only get a left channel, which others have reported on up-to-date official SteamOS as well.  Some have apparently RMA'd their units, so maybe I have a defective one too?

'''
<<<
== Input Devices
The Steam Deck has a few input interfaces, and has been the primary focus of my work with the device.

{nbsp} +
{nbsp}

'''
=== USB interface

.lsusb
[%collapsible%open]
====
----
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 13d3:3553 IMC Networks Bluetooth Radio
Bus 003 Device 002: ID 28de:1205 Valve Software Steam Deck Controller
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
----
====

Most the available inputs appear to be attached to the internal USB3 bus, which makes it pretty easy to get access to.  Even without explicit drivers, the hidraw subsystem makes these available in `/dev/hidraw*`.  They can also be accessed via low-level USB APIs.

This is my dev system, so I have OpenSD udev rules installed.
----
crw-rw---- 1 root opensd 241, 0 Nov 21 10:48 /dev/hidraw0
crw-rw---- 1 root opensd 241, 1 Nov 21 10:48 /dev/hidraw1
crw------- 1 root root   241, 2 Nov 21 10:48 /dev/hidraw2
crw-rw---- 1 root opensd 241, 3 Nov 21 10:48 /dev/hidraw3
----

In this case, `hidraw0`, `hidraw1` and `hidraw3` are all the same USB device for the "Steam Deck Controller", which is _most_ of the user-facing input features (buttons, sticks, triggers, pads, etc).  `hidraw2` is the touchscreen device, which I'll get into later.

The gamepad USB interface looks like this:

.lsusb -v -d28de:1205
[%collapsible%open]
====
----
Bus 003 Device 002: ID 28de:1205 Valve Software Steam Deck Controller
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          239 Miscellaneous Device
  bDeviceSubClass         2 
  bDeviceProtocol         1 Interface Association
  bMaxPacketSize0        64
  idVendor           0x28de Valve Software
  idProduct          0x1205 
  bcdDevice            2.00
  iManufacturer           1 Valve Software
  iProduct                2 Steam Deck Controller
  iSerial                 3 MEDA228045B1
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0096
    bNumInterfaces          5
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0                         <----------------- <1>
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      39
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1                         <----------------- <2>
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      50
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2                         <----------------- <3>
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      29
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Association:
      bLength                 8
      bDescriptorType        11
      bFirstInterface         3
      bInterfaceCount         2
      bFunctionClass          2 Communications
      bFunctionSubClass       2 Abstract (modem)
      bFunctionProtocol       1 AT-commands (v.25ter)
      iFunction               0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         2 Communications
      bInterfaceSubClass      2 Abstract (modem)
      bInterfaceProtocol      1 AT-commands (v.25ter)
      iInterface              0 
      CDC Header:
        bcdCDC               1.10
      CDC Call Management:
        bmCapabilities       0x01
          call management
        bDataInterface          2
      CDC ACM:
        bmCapabilities       0x02
          line coding and serial state
      CDC Union:
        bMasterInterface        3
        bSlaveInterface         4 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval             255
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        4
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass        10 CDC Data
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x05  EP 5 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
Device Status:     0x0000
  (Bus Powered)
----
<1> "Lizard Mode" keyboard HID
<2> "Lizard Mode" mouse HID
<3> Gamepad / master HID
====

As the callouts indicate above, this USB device has 3 HID-class sub-devices.  The first two are explained in more detail in the <<lizard_mode>> section below, but they are, in a sense, child devices of the third (`bInterfaceNum 2`) sub-device, which is the gamepad.

The gamepad interface sends input reports which contain (nearly) all the user-facing input states, including the trackpads which produce data for the "Lizard Mode" mouse sub-device uses.  The gamepad interface can also written to and is used to receive feature reports, whereas the the other two interfaces *cannot* receive feature reports.  The "Lizard Mode" mouse/keyboard interfaces can be *disabled*, but *only* by sending a feature report to the gamepad interface.  This essentially makes the gamepad the *master* sub-device.

Reading and writing this interface can be done in the usual ways, as with other USB and HID-class devices, so I wont go into how to use those APIs, but I do get into the HID report numbers, structures, etc which are are at the heart of OpenSD, in the <<hid_reports>> section.

{nbsp} +
{nbsp}

'''
<<<
[#input_event_devices]
=== Input Event Devices

evtest

----
/dev/input/event0:	Power Button
/dev/input/event1:	Lid Switch
/dev/input/event2:	Power Button
/dev/input/event3:	AT Translated Set 2 keyboard
/dev/input/event4:	Video Bus
/dev/input/event5:	Valve Software Steam Deck Controller
/dev/input/event6:	Valve Software Steam Deck Controller
/dev/input/event7:	acp5x Headset Jack
/dev/input/event8:	FTS3528:00 2808:1015
/dev/input/event9:	HD-Audio Generic HDMI/DP,pcm=3
/dev/input/event10:	HD-Audio Generic HDMI/DP,pcm=7
/dev/input/event11:	HD-Audio Generic HDMI/DP,pcm=8
/dev/input/event12:	HD-Audio Generic HDMI/DP,pcm=9
/dev/input/event13:	PC Speaker
/dev/input/event14:	FTS3528:00 2808:1015 UNKNOWN
----

There are a few notable event nodes here:  the `Valve Software Steam Deck Controller`, `AT Translated Set 2 keyboard`, `Power Button` and the `FTS3528` devices.

Gamepad::
The two "Valve Software Steam Deck Controller" devices (`event5` and `event6`) Are the "Lizard Mode" mouse and keyboard devices.  

Volume::
Interestingly, the two *volume buttons*, `+` `-` on the top of the Steam Deck are not part of the rest of the gamepad input reports.  They are connected to the `AT Translated Set 2 keyboard` (`event3`) device, which appears as an entire PS/2(?) keyboard:

.evtest /dev/input/event3
[%collapsible%open]
====
----
Input device ID: bus 0x11 vendor 0x1 product 0x1 version 0xab83
Input device name: "AT Translated Set 2 keyboard"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 1 (KEY_ESC)
    Event code 2 (KEY_1)
    Event code 3 (KEY_2)
    Event code 4 (KEY_3)
    Event code 5 (KEY_4)
    Event code 6 (KEY_5)
    Event code 7 (KEY_6)
    Event code 8 (KEY_7)
    Event code 9 (KEY_8)
    Event code 10 (KEY_9)
    Event code 11 (KEY_0)
    Event code 12 (KEY_MINUS)
    Event code 13 (KEY_EQUAL)
    Event code 14 (KEY_BACKSPACE)
    Event code 15 (KEY_TAB)
    Event code 16 (KEY_Q)
    Event code 17 (KEY_W)
    Event code 18 (KEY_E)
    Event code 19 (KEY_R)
    Event code 20 (KEY_T)
    Event code 21 (KEY_Y)
    Event code 22 (KEY_U)
    Event code 23 (KEY_I)
    Event code 24 (KEY_O)
    Event code 25 (KEY_P)
    Event code 26 (KEY_LEFTBRACE)
    Event code 27 (KEY_RIGHTBRACE)
    Event code 28 (KEY_ENTER)
    Event code 29 (KEY_LEFTCTRL)
    Event code 30 (KEY_A)
    Event code 31 (KEY_S)
    Event code 32 (KEY_D)
    Event code 33 (KEY_F)
    Event code 34 (KEY_G)
    Event code 35 (KEY_H)
    Event code 36 (KEY_J)
    Event code 37 (KEY_K)
    Event code 38 (KEY_L)
    Event code 39 (KEY_SEMICOLON)
    Event code 40 (KEY_APOSTROPHE)
    Event code 41 (KEY_GRAVE)
    Event code 42 (KEY_LEFTSHIFT)
    Event code 43 (KEY_BACKSLASH)
    Event code 44 (KEY_Z)
    Event code 45 (KEY_X)
    Event code 46 (KEY_C)
    Event code 47 (KEY_V)
    Event code 48 (KEY_B)
    Event code 49 (KEY_N)
    Event code 50 (KEY_M)
    Event code 51 (KEY_COMMA)
    Event code 52 (KEY_DOT)
    Event code 53 (KEY_SLASH)
    Event code 54 (KEY_RIGHTSHIFT)
    Event code 55 (KEY_KPASTERISK)
    Event code 56 (KEY_LEFTALT)
    Event code 57 (KEY_SPACE)
    Event code 58 (KEY_CAPSLOCK)
    Event code 59 (KEY_F1)
    Event code 60 (KEY_F2)
    Event code 61 (KEY_F3)
    Event code 62 (KEY_F4)
    Event code 63 (KEY_F5)
    Event code 64 (KEY_F6)
    Event code 65 (KEY_F7)
    Event code 66 (KEY_F8)
    Event code 67 (KEY_F9)
    Event code 68 (KEY_F10)
    Event code 69 (KEY_NUMLOCK)
    Event code 70 (KEY_SCROLLLOCK)
    Event code 71 (KEY_KP7)
    Event code 72 (KEY_KP8)
    Event code 73 (KEY_KP9)
    Event code 74 (KEY_KPMINUS)
    Event code 75 (KEY_KP4)
    Event code 76 (KEY_KP5)
    Event code 77 (KEY_KP6)
    Event code 78 (KEY_KPPLUS)
    Event code 79 (KEY_KP1)
    Event code 80 (KEY_KP2)
    Event code 81 (KEY_KP3)
    Event code 82 (KEY_KP0)
    Event code 83 (KEY_KPDOT)
    Event code 85 (KEY_ZENKAKUHANKAKU)
    Event code 86 (KEY_102ND)
    Event code 87 (KEY_F11)
    Event code 88 (KEY_F12)
    Event code 89 (KEY_RO)
    Event code 90 (KEY_KATAKANA)
    Event code 91 (KEY_HIRAGANA)
    Event code 92 (KEY_HENKAN)
    Event code 93 (KEY_KATAKANAHIRAGANA)
    Event code 94 (KEY_MUHENKAN)
    Event code 95 (KEY_KPJPCOMMA)
    Event code 96 (KEY_KPENTER)
    Event code 97 (KEY_RIGHTCTRL)
    Event code 98 (KEY_KPSLASH)
    Event code 99 (KEY_SYSRQ)
    Event code 100 (KEY_RIGHTALT)
    Event code 102 (KEY_HOME)
    Event code 103 (KEY_UP)
    Event code 104 (KEY_PAGEUP)
    Event code 105 (KEY_LEFT)
    Event code 106 (KEY_RIGHT)
    Event code 107 (KEY_END)
    Event code 108 (KEY_DOWN)
    Event code 109 (KEY_PAGEDOWN)
    Event code 110 (KEY_INSERT)
    Event code 111 (KEY_DELETE)
    Event code 112 (KEY_MACRO)
    Event code 113 (KEY_MUTE)
    Event code 114 (KEY_VOLUMEDOWN)
    Event code 115 (KEY_VOLUMEUP)
    Event code 116 (KEY_POWER)
    Event code 117 (KEY_KPEQUAL)
    Event code 118 (KEY_KPPLUSMINUS)
    Event code 119 (KEY_PAUSE)
    Event code 121 (KEY_KPCOMMA)
    Event code 122 (KEY_HANGUEL)
    Event code 123 (KEY_HANJA)
    Event code 124 (KEY_YEN)
    Event code 125 (KEY_LEFTMETA)
    Event code 126 (KEY_RIGHTMETA)
    Event code 127 (KEY_COMPOSE)
    Event code 128 (KEY_STOP)
    Event code 140 (KEY_CALC)
    Event code 142 (KEY_SLEEP)
    Event code 143 (KEY_WAKEUP)
    Event code 155 (KEY_MAIL)
    Event code 156 (KEY_BOOKMARKS)
    Event code 157 (KEY_COMPUTER)
    Event code 158 (KEY_BACK)
    Event code 159 (KEY_FORWARD)
    Event code 163 (KEY_NEXTSONG)
    Event code 164 (KEY_PLAYPAUSE)
    Event code 165 (KEY_PREVIOUSSONG)
    Event code 166 (KEY_STOPCD)
    Event code 172 (KEY_HOMEPAGE)
    Event code 173 (KEY_REFRESH)
    Event code 183 (KEY_F13)
    Event code 184 (KEY_F14)
    Event code 185 (KEY_F15)
    Event code 217 (KEY_SEARCH)
    Event code 226 (KEY_MEDIA)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
  Event type 17 (EV_LED)
    Event code 0 (LED_NUML) state 0
    Event code 1 (LED_CAPSL) state 0
    Event code 2 (LED_SCROLLL) state 0
Key repeat handling:
  Repeat type 20 (EV_REP)
    Repeat code 0 (REP_DELAY)
      Value    250
    Repeat code 1 (REP_PERIOD)
      Value     33
----
====

However, the only(?) physical buttons in use are the two volume keys, which emit the expected `KEY_VOLUMEUP` and `KEY_VOLUMEDOWN` events.

Power::
I haven't played with this too much, but it looks like a standard ACPI power button.

Touchscreen::
The `FTS3528:00 2808:10151` (event8) and `FTS3528:00 2808:1015 UNKNOWN` (event14) are the touchscreen devices.  They both appear to connect via the https://en.wikipedia.org/wiki/I%C2%B2S[i2s] bus as a single HID device (as noted about hidraw nodes earlier), with two interfaces.  Raw touchscreen input can be read using the kernel hidraw interface.  It uses *60-byte input reports*, which I have not yet decoded.

Like the display manufacturer, this is a bit mysterious.  There's a decent chance that the display manufacturer and the touchscreen sensor manufacturer are not the same.  Doing a quick search about this thing didn't reveal much.  Eventually I'll probably dig into the origins a bit more.

It should be noted that, like the display, the native orientation is *portrait / full page*, rather than *landscape / widescreen* as it's oriented on the Steam Deck.  So, while X and Wayland can use them, both the screen coordinates and the input coordinates need to be transformed (unless you hate your neck).  I've given instructions on how to do this with X in the <<display>> section.

`FTS3528:00 2808:10151` (event8):: 
This is the touchscreen input which works out of the box, at least on the kernels I've tested.  It supports these events:

.evtest /dev/input/event8
[%collapsible%open]
====
----
Input driver version is 1.0.1
Input device ID: bus 0x18 vendor 0x2808 product 0x1015 version 0x100
Input device name: "FTS3528:00 2808:1015"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 330 (BTN_TOUCH)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    204
      Min        0
      Max      800
      Resolution       3
    Event code 1 (ABS_Y)
      Value   1031
      Min        0
      Max     1280
      Resolution       9
    Event code 47 (ABS_MT_SLOT)
      Value      0
      Min        0
      Max        9
    Event code 48 (ABS_MT_TOUCH_MAJOR)
      Value      0
      Min        0
      Max      255
      Resolution      10
    Event code 49 (ABS_MT_TOUCH_MINOR)
      Value      0
      Min        0
      Max      255
      Resolution      10
    Event code 52 (ABS_MT_ORIENTATION)
      Value      0
      Min        0
      Max        1
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max      800
      Resolution       3
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        0
      Max     1280
      Resolution       9
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max    65535
    Event code 60 (ABS_MT_TOOL_X)
      Value      0
      Min        0
      Max      800
      Resolution       3
    Event code 61 (ABS_MT_TOOL_Y)
      Value      0
      Min        0
      Max     1280
      Resolution       9
  Event type 4 (EV_MSC)
    Event code 5 (MSC_TIMESTAMP)
Properties:
  Property type 1 (INPUT_PROP_DIRECT)
----
====

I need to spend more time playing around with this, but it appears to support at least 2-point multi-touch.


`FTS3528:00 2808:1015 UNKNOWN` (event14):: 
This appears(?) to be a stylus interface, however I cannot get it to produce any events.  I've tried a few styluses I have lying around and... nada.  nothing.  It might not actually have this feature at all and it's just the firmware.  I'd be interested to know if anyone has gotten this to work.  It supports the following events:

.evtest /dev/input/event14
[%collapsible%open]
====
----
Input driver version is 1.0.1
Input device ID: bus 0x18 vendor 0x2808 product 0x1015 version 0x100
Input device name: "FTS3528:00 2808:1015 UNKNOWN"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 320 (BTN_TOOL_PEN)
    Event code 330 (BTN_TOUCH)
    Event code 331 (BTN_STYLUS)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value      0
      Min        0
      Max     4095
      Resolution      14
    Event code 1 (ABS_Y)
      Value      0
      Min        0
      Max     4095
      Resolution      25
    Event code 24 (ABS_PRESSURE)
      Value      0
      Min        1
      Max      255
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
----
====

{nbsp} +
{nbsp}

'''
<<<
[#lizard_mode]
=== Lizard Mode
The Steam Deck, as with the Steam Controller, has a kind of fallback "BIOS mode" functionality, which emulates some basic mouse and keyboard functions, like arrow keys, enter, left and right mouse buttons.  These are *sub-devices* of the gamepad, and rely on the data that the gamepad device produces to emit input events.  They each have their own interface number on the main USB HID.  This mode is *enabled* by default and immediately available at boot, which is how you navigate the UEFI / BIOS bootloader screens.

These two devices *do not* send joystick events, even though they are driven by joystick input.  Steam implements a proprietaty userspace driver _from within the client itself_ to access the gamepad input leaving all other applications with a crippled "Lizard Mode" fallback input system.  

When the Steam client connects the the gamepad device, it sends a feature report to *temporarily* disable the "Lizard Mode" mouse and keyboard from sending input events.  These will remain disabled for a few seconds, then automatically re-enable themselves, presumably to prevent the device from becoming *completely* unusable if Steam exits or crashes.  These feature reports must continually be sent every couple seconds to prevent them from re-enabling.  This report is only send to the master/gamepad interface of the USB device (`bInterfaceNum 2`), the other two (`bInterfaceNum 0` and `bInterfaceNum 1`) devices cannot be written to.  See the <<hid_reports>> section for more information on these reports, and see the https://gitlab.com/open-sd/opensd[OpenSD] source code for a multi-threaded implementation.

When "Lizard Mode" is *not* disabled, these devices will continue to send input event codes even if you are correctly decoding the raw gamepad input reports, so it is necessary to disable them in order to use the _actual_ gamepad input or you will get multiple events emitted from several buttons, as well as multiple mouse 

{nbsp} +
{nbsp}

'''
<<<
[#hid_reports]
=== HID Reports
There are at least two HID devices worth exploring here, so I'll break them down into sections for each device.

'''
<<<
==== Steam Deck Contoller
The Steam Deck gamepad / controller uses a report structure similar to the Steam Controller, which makes a lot of sense.  In a way, the Steam Deck could be considered the Steam Controller 2, since it generally improves on the older design and adds more features.  

Polling rate on this device seems(?) to be fixed to 250Hz, which is on the low end of USB polling, but it's debatable if more is really necessary.  It's also possible there's an issue with the kernel or udev which limits it.

{nbsp} +
{nbsp}

===== Report IDs
I've found most of the report numbers are the same as the SC, so I've used the SC kernel driver for a bit of reference to their names.
[source]
----
INPUT                       = 0x01
SET_MAPPINGS                = 0x80
CLEAR_MAPPINGS              = 0x81
GET_MAPPINGS                = 0x82
GET_ATTRIB                  = 0x83
GET_ATTRIB_LABEL            = 0x84
DEFAULT_MAPPINGS            = 0x85
FACTORY_RESET               = 0x86
WRITE_REGISTER              = 0x87
CLEAR_REGISTER              = 0x88
READ_REGISTER               = 0x89
GET_REGISTER_LABEL          = 0x8a
GET_REGISTER_MAX            = 0x8b
GET_REGISTER_DEFAULT        = 0x8c
SET_MODE                    = 0x8d
DEFAULT_MOUSE               = 0x8e
FORCE_FEEDBACK              = 0x8f
REQUEST_COMM_STATUS         = 0xb4
GET_SERIAL                  = 0xae
----


{nbsp} +
{nbsp}

===== Registers
Thse are for programming the controller with the `WRITE_REGISTER`, `READ_REGISTER` and `CLEAR_REGISTER` reports.

[source]
----
LPAD_MODE                   = 0x07
RPAD_MODE                   = 0x08
RPAD_MARGIN                 = 0x18
GYRO_MODE                   = 0x30
----

{nbsp} +
{nbsp}

===== Report Sizes
These are the size of the HID reports in bytes / octets
[source]
----
INPUT                       = 64
HAPTIC                      = 7(?)
CONFIG                      = 21(?)
----

I still have more work to do on FF support, so I'm not sure of the numbers with "(?)"s

{nbsp} +
{nbsp}

===== Input Report
This is the input report packet that contains nearly every input state on the Steam Deck.

The report size is 64 bytes long and can be read as a tightly packed struct in this order.  This is a slightly reformatted copy of the code that OpenSD uses.

----

     Name       Bits    Type    Byte Num                             Description                            

 report_id         8  uint8_t        0    HID input report ID                                               
 _unk0             8  uint8_t        1    Always returns 0. Possibly USAGE PAGE?                            
 _unk1             8  uint8_t        2    Always returns 9. Possibly status like SC?  Could also be USAGE?  
 report_size       8  uint8_t        3    Appears to be the length of report in bytes.  Always returns 64.  
 frame            32  uint32_t       4    Looks like a linear counter for input frames                      
 r2                1  bool           8.0  Binary sensor for analogue triggers                               
 l2                1  bool           8.1                                                                   
 r1                1  bool           8.2  Shoulder buttons                                                  
 l1                1  bool           8.3                                                                   
 y                 1  bool           8.4  Button cluster                                                    
 b                 1  bool           8.5                                                                   
 x                 1  bool           8.6                                                                   
 a                 1  bool           8.7                                                                   
 up                1  bool           9.0  Directional Pad buttons                                           
 right             1  bool           9.1                                                                   
 left              1  bool           9.2                                                                   
 down              1  bool           9.3                                                                   
 options           1  bool           9.4  View / Overlapping square   button located above left stick      
 steam             1  bool           9.5  STEAM button below left trackpad                                  
 menu              1  bool           9.6  Hamburger () button located above right stick                    
 l5                1  bool           9.7  L5 & R5 on the back of the deck                                   
 r5                1  bool          10.0                                                                   
 l_pad_press       1  bool          10.1  Binary press sensor for trackpads                                 
 r_pad_press       1  bool          10.2                                                                   
 l_pad_touch       1  bool          10.3  Binary touch sensor for trackpads                                 
 r_pad_touch       1  bool          10.4                                                                   
 _unk3             1  bool          10.5  Unknown                                                           
 l3                1  bool          10.6  Z-axis button on the left stick                                   
 _unk4             1  bool          10.7  Unknown                                                           
 _unk5             1  bool          11.0                                                                   
 _unk6             1  bool          11.1                                                                   
 r3                1  bool          11.2  Z-axis button on the right stick                                  
 _unk7             1  bool          11.3  Unknown                                                           
 _unk8             1  bool          11.4                                                                   
 _unk9             1  bool          11.5                                                                   
 _unk10            1  bool          11.6                                                                   
 _unk11            1  bool          11.7                                                                   
 _unk12            1  bool          12.0  No readings on any of these.                                      
 _unk13            1  bool          12.1                                                                   
 _unk14            1  bool          12.2                                                                   
 _unk15            1  bool          12.3                                                                   
 _unk16            1  bool          12.4                                                                   
 _unk17            1  bool          12.5                                                                   
 _unk18            1  bool          12.6                                                                   
 _unk19            1  bool          12.7                                                                   
 _unk20            1  bool          13.0                                                                   
 l4                1  bool          13.1  L4 & R4 on the back of the deck                                   
 r4                1  bool          13.2                                                                   
 _unk21            1  bool          13.3  Unknown                                                           
 _unk22            1  bool          13.4                                                                   
 _unk23            1  bool          13.5                                                                   
 l_stick_touch     1  bool          13.6  Binary touch sensors on the stick controls                        
 r_stick_touch     1  bool          13.7                                                                   
 _unk24            1  bool          14.0  Unknown                                                           
 _unk25            1  bool          14.1                                                                   
 quick_access      1  bool          14.2  Quick Access (...) button below right trackpad                    
 _unk26            1  bool          14.3  Unknown                                                           
 _unk27            1  bool          14.4                                                                   
 _unk28            1  bool          14.5                                                                   
 _unk29            1  bool          14.6                                                                   
 _unk30            1  bool          14.7                                                                   
 _unk31            8  uint8_t       15    Not sure, maybe padding or just unused                            
 l_pad_x          16  int16_t       16    Trackpad touch coordinates                                        
 l_pad_y          16  int16_t       18                                                                     
 r_pad_x          16  int16_t       20                                                                     
 r_pad_y          16  int16_t       22                                                                     
 accel_x          16  int16_t       24    Accelerometers I think.  Needs more testing.                      
 accel_y          16  int16_t       26                                                                     
 accel_z          16  int16_t       28                                                                     
 pitch            16  int16_t       30    Attitude (?)  Needs more testing.                                 
 yaw              16  int16_t       32                                                                     
 roll             16  int16_t       34                                                                     
 _gyro0           16  int16_t       36    Not sure what these are...                                        
 _gyro1           16  int16_t       38    Seems like they might be additional gyros for extra precision (?) 
 _gyro2           16  int16_t       40                                                                     
 _gyro3           16  int16_t       42                                                                     
 l_trigg          16  uint16_t      44    Pressure sensors for L2 & R2 triggers                             
 r_trigg          16  uint16_t      46                                                                     
 l_stick_x        16  int16_t       48    Analogue thumbsticks                                              
 l_stick_y        16  int16_t       50                                                                     
 r_stick_x        16  int16_t       52                                                                     
 r_stick_y        16  int16_t       54                                                                     
 l_pad_force      16  uint16_t      56    Touchpad pressure sensors                                         
 r_pad_force      16  uint16_t      58                                                                     
 l_stick_force    16  uint16_t      60    Thumbstick capacitive sensors                                     
 r_stick_force    16  uint16_t      62                                                                     

----

'''
<<<
== Bootloader
To access the bootloader, turn off the Steam Deck.  With the power off, hold down the "Volume Down" (`(-)` button on top of the Steam Deck) and press power.  Keep holding the button until it makes a beep/chime sound.

*TODO*


